service: hotosm-slack-router
provider:
  name: aws
  runtime: nodejs10.x

stage: dev
region: us-east-1

functions:
  github:
    handler: easyIssues.easyIssues
    events:
      - http:
          path: api/github
          method: post
          cors: true