service: hotosm-slack-router
provider:
  name: aws
  runtime: nodejs10.x

stage: dev
region: us-east-1

functions:
  easyIssues:
    handler: easyIssues.easyIssues
    events:
      - http:
          path: api/easyissues
          method: post
          cors: true
  healthCheck:
    handler: healthCheck.healthCheck
    events:
      - http:
          path: api/healthcheck
          method: post
          cors: true
  projectStats:
    handler: projectStats.projectStats
    events:
      - http:
          path: api/projectstats
          method: post
          cors: true
