service: hotosm-slack-router
provider:
  name: aws
  runtime: nodejs10.x

stage: dev
region: us-east-1

functions:
  easyIssues:
    handler: easy-issues.handler
    events:
      - http:
          path: api/easyissues
          method: post
          cors: true
  healthCheck:
    handler: health-check.handler
    events:
      - http:
          path: api/healthcheck
          method: post
          cors: true
  projectStats:
    handler: project-stats.handler
    events:
      - http:
          path: api/projectstats
          method: post
          cors: true
  osmchaSuspect:
    handler: osmcha-suspect.handler
    events:
      - http:
          path: api/osmchasuspect
          method: post
          cors: true
