service: hotosm-slack-router
provider:
  name: aws
  runtime: nodejs10.x

stage: dev
region: us-east-1

functions:
  easyIssues:
    handler: easy-issues.easyIssues
    events:
      - http:
          path: api/easyissues
          method: post
          cors: true
  healthCheck:
    handler: health-check.healthCheck
    events:
      - http:
          path: api/healthcheck
          method: post
          cors: true
  projectStats:
    handler: project-stats.projectStats
    events:
      - http:
          path: api/projectstats
          method: post
          cors: true
  slackEvents:
    handler: slack-events/slackEvents
    events:
      - http:
          path: api/slackevents
          method: post
          cors: true
